import Head from "next/head";
import styles from "../styles/Portfolio.module.css";
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>joyetgeorge.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-3 sm:mx-32">
        <div className="landing xl:h-screen grid grid-cols-1  h-screen">
          <div className="self-center">
            <h1 className="text-5xl font-extrabold md:text-8xl">
              Hello, I&apos;m Joyet
            </h1>
            <p className="md:text-2xl xl:w-1/2">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. In
              minima cupiditate blanditiis ipsa adipisci aliquid molestiae,
              nulla ipsam amet assumenda iste dicta quae magni culpa fugit
              soluta possimus quod debitis.
            </p>
            <div className="resume w-10">
              <h1 className="text-black hover:text-red-600 ">
                <span className="text-3xl ">
                  <a
                    className="text-black hover:text-red-600"
                    href="https://raw.githubusercontent.com/joyetgeorge/resume/main/Joyet%20George%20%5BResume%5D%20(1).pdf"
                  >
                    Résumé
                  </a>
                </span>
                <span className="ml-5">
                  <span>→</span>
                </span>
              </h1>
            </div>
          </div>
          <div className="bottom-3 absolute">
            <a className="text-2xl text-black hover:text-red-600" href="">
              GitHub
            </a>
            <a className="text-2xl text-black hover:text-red-600 ml-10" href="">
              Linkedin
            </a>
            <a className="text-2xl text-black hover:text-red-600 ml-10" href="">
              Instagram
            </a>
          </div>
        </div>
        <div className="mt-32 md:mt-10">
          <div className="grid sm:grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-4 xl:mt-10">
            <h1 className="text-4xl font-extrabold sm:col-span-2 sm:grid sm:grid-cols-2 sm:gap-4 md:text-7xl md:self-center xl:col-span-3 xl:text-8xl ">
              <span>Some of my Works.</span>
              <div className="self-center">
                <h1 className="md:text-6xl hidden md:block">→</h1>
              </div>
            </h1>
            <p className="sm:row-start-2 sm:col-start-2 sm:self-center md:self-center md:col-start-1 md:text-2xl">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto
              necessitatibus ullam sapiente totam saepe accusamus, est mollitia
              soluta magni dicta.
            </p>
            <a href="#">
              <div className="group bg-white aspect-square sm:h-auto sm:aspect-square overflow-hidden relative">
                <div className="bottom-1 absolute">
                  <h1 className="hidden group-hover:block mx-5 text-black xl:text-3xl">
                    Atheneum
                  </h1>
                  <p className="hidden group-hover:block text-black mx-5 ">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Fuga, molestias.
                  </p>
                </div>
                <img
                  className="object-cover h-full w-full hover:opacity-50 hover:border-2 hover:border-black hover:duration-300 border-2"
                  src="https://raw.githubusercontent.com/joyetgeorge/Atheneum/master/Atheneum.png"
                  alt=""
                />
              </div>
            </a>
            <a href="#">
              <div className="group bg-white sm:h-auto sm:aspect-square overflow-hidden relative">
                <div className="bottom-1 absolute">
                  <h1 className="hidden text-black group-hover:block mx-5 xl:text-3xl">
                    Sunday Readings
                  </h1>
                  <p className="hidden text-black group-hover:block mx-5 ">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Fuga, molestias.
                  </p>
                </div>
                <img
                  className="object-cover h-full w-full hover:opacity-50 hover:border-2 hover:border-black hover:duration-300 border-2"
                  src="https://raw.githubusercontent.com/joyetgeorge/Sunday-Readings-in-Pochury/main/Sunday.png"
                  alt=""
                />
              </div>
            </a>
            <a href="#">
              <div className="group bg-white sm:h-auto sm:aspect-square overflow-hidden relative">
                <div className="bottom-1 absolute">
                  <h1 className="hidden group-hover:block text-black mx-5 xl:text-3xl">
                    Snake
                  </h1>
                  <p className="hidden group-hover:block mx-5 text-black ">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Fuga, molestias.
                  </p>
                </div>
                <img
                  className="object-cover h-full w-full hover:opacity-50 hover:border-2 hover:border-black hover:duration-300 border-2"
                  src="https://raw.githubusercontent.com/joyetgeorge/store/main/snake.gif"
                  alt=""
                />
              </div>
            </a>
            <a href="#">
              <div className="group bg-white sm:h-auto sm:aspect-square overflow-hidden relative">
                <div className="bottom-1 absolute">
                  <h1 className="hidden text-black group-hover:block mx-5 xl:text-3xl">
                    Calculator
                  </h1>
                  <p className="hidden text-black group-hover:block mx-5 ">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Fuga, molestias.
                  </p>
                </div>
                <img
                  className="object-cover h-full w-full hover:opacity-50 hover:border-2 hover:border-black hover:duration-300 border-2"
                  src="https://raw.githubusercontent.com/joyetgeorge/Calculator/master/c.png"
                  alt=""
                />
              </div>
            </a>
            <a href="#">
              <div className="group bg-white sm:h-auto sm:aspect-square overflow-hidden relative">
                <div className="bottom-1 absolute">
                  <h1 className="hidden text-black group-hover:block mx-5 xl:text-3xl">
                    Flash Light
                  </h1>
                  <p className="hidden text-black group-hover:block mx-5 ">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Fuga, molestias.
                  </p>
                </div>
                <img
                  className="object-cover h-full w-full hover:opacity-50 hover:border-2 hover:border-black hover:duration-300 border-2"
                  src="https://raw.githubusercontent.com/joyetgeorge/FlashLight/master/flash.png"
                  alt=""
                />
              </div>
            </a>
            <a href="#">
              <div className="group bg-white sm:h-auto sm:aspect-square overflow-hidden relative">
                <div className="bottom-1 absolute">
                  <h1 className="hidden text-black group-hover:block mx-5 xl:text-3xl">
                    Space-Invaders
                  </h1>
                  <p className="hidden text-black group-hover:block mx-5 ">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Fuga, molestias.
                  </p>
                </div>
                <img
                  className="object-cover h-full w-full hover:opacity-50 hover:border-2 hover:border-black hover:duration-300 border-2"
                  src="https://raw.githubusercontent.com/joyetgeorge/Space-Invaders-Pygame/main/space.gif"
                  alt=""
                />
              </div>
            </a>
            <a href="#">
              <div className="group bg-white sm:h-auto sm:aspect-square overflow-hidden relative">
                <div className="bottom-1 absolute">
                  <h1 className="hidden text-black group-hover:block mx-5 xl:text-3xl">
                    Linux Post Installer
                  </h1>
                  <p className="hidden text-black group-hover:block mx-5 ">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Fuga, molestias.
                  </p>
                </div>
                <img
                  className="object-cover h-full w-full hover:opacity-50 hover:border-2 hover:border-black hover:duration-300 border-2"
                  src="https://raw.githubusercontent.com/joyetgeorge/Linux-post-installer/main/linux.png"
                  alt=""
                />
              </div>
            </a>
            <p className="sm:self-center sm:text-2xl">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto
              necessitatibus ullam sapiente totam saepe accusamus, est mollitia
              soluta magni dicta.
            </p>
          </div>
        </div>
        <h1 className="text-4xl mt-32 font-extrabold xl:text-6xl xl:mt-60">
          <span>Work experience.</span>
        </h1>
        <div className="grid gap-4 grid-cols-1 mt-10">
          <div className="group border-2  border-black hover:bg-black hover:duration-300 xl:h-16 md:h-10 sm:h-auto grid grid-cols-5 h-12">
            <h1 className="self-center group-hover:text-white col-span-2 font-extrabold ml-3 text-2xl md:ml-10">
              BerryWorks
            </h1>
            <h1 className="self-center group-hover:text-white col-span-3 ml-10 md:ml-0 md:col-span-1 text-lg md:text-2xl">
              Full-Stack Developer
            </h1>
            <h1 className="self-center group-hover:text-white hidden md:block">
              Current
            </h1>
            <div className="self-center mr-3 md:mr-10 group-hover:text-white">
              <div className="self-center border-2 group-hover:border-white border-black w-10 h-10 float-right text-center content-center rounded-full hidden md:block">
                <h1 className="">→</h1>
              </div>
            </div>
          </div>
          <div className="group border-2  border-black hover:bg-black hover:duration-300 xl:h-16 md:h-10 sm:h-auto grid grid-cols-5 h-12">
            <h1 className="self-center group-hover:text-white col-span-2 font-extrabold text-2xl ml-3 md:ml-10">
              Fiverr
            </h1>
            <h1 className="self-center group-hover:text-white col-span-3 ml-10 md:ml-0 md:col-span-1 text-lg md:text-2xl">
              Full-Stack Developer
            </h1>
            <h1 className="self-center group-hover:text-white hidden md:block">
              
            </h1>
            <div className="self-center mr-3 md:mr-10 group-hover:text-white">
              <div className="self-center border-2 group-hover:border-white border-black w-10 h-10 float-right text-center content-center rounded-full hidden md:block">
                <h1 className="">→</h1>
              </div>
            </div>
          </div>
          <div className="group border-2  border-black hover:bg-black hover:duration-300 xl:h-16 md:h-10 sm:h-auto grid grid-cols-5 h-12">
            <h1 className="self-center group-hover:text-white col-span-2 font-extrabold text-2xl ml-3 md:ml-10">
              Freelancer
            </h1>
            <h1 className="self-center group-hover:text-white col-span-3 ml-10 md:ml-0 md:col-span-1 text-lg md:text-2xl">
              Flutter Developer
            </h1>
            <h1 className="self-center group-hover:text-white hidden md:block">
             
            </h1>
            <div className="self-center mr-3 md:mr-10 group-hover:text-white">
              <div className="self-center border-2 group-hover:border-white border-black w-10 h-10 float-right text-center content-center rounded-full hidden md:block">
                <h1 className="">→</h1>
              </div>
            </div>
          </div>
        </div>
        <div className="gap-4 grid-cols-8 grid mt-10 mb-30 px-3 md:px-0">
          <div className="flex items-center justify-center h-8 md:16 sm:h-auto aspect-square">
            <Image
              className=""
              src="https://cdn4.iconfinder.com/data/icons/logos-brands-5/24/react-256.png"
              unoptimized
              height="60px"
              width="60px"
              alt=""
            ></Image>
          </div>
          <div className=" flex items-center justify-center h-8 md:16 sm:h-auto aspect-square">
            <Image
              src="https://cdn4.iconfinder.com/data/icons/logos-brands-5/24/flutter-512.png"
              unoptimized
              height="60px"
              width="60px"
              alt=""
            ></Image>
          </div>
          <div className=" flex items-center justify-center h-8 md:16 sm:h-auto aspect-square">
            <Image
              src="https://cdn3.iconfinder.com/data/icons/font-awesome-brands/512/linux-256.png"
              unoptimized
              height="60px"
              width="60px"
              alt=""
            ></Image>
          </div>
          <div className=" flex items-center justify-center h-8 md:16 sm:h-auto aspect-square">
            <Image
              src="https://cdn3.iconfinder.com/data/icons/font-awesome-brands/512/figma-512.png"
              unoptimized
              height="60px"
              width="60px"
              alt=""
            ></Image>
          </div>
          <div className=" flex items-center justify-center h-8 md:16 sm:h-auto aspect-square">
            <Image
              src="https://cdn1.iconfinder.com/data/icons/bootstrap-fill-vol-2/16/git-256.png"
              unoptimized
              height="60px"
              width="60px"
            ></Image>
          </div>
          <div className=" flex items-center justify-center h-8 md:16 sm:h-auto aspect-square">
            <Image
              src="https://cdn2.iconfinder.com/data/icons/boxicons-logos/24/bxl-firebase-256.png"
              unoptimized
              height="60px"
              width="60px"
              alt=""
            ></Image>
          </div>
          <div className=" flex items-center justify-center h-8 md:16 sm:h-auto aspect-square">
            <Image
              src="https://cdn3.iconfinder.com/data/icons/logos-and-brands-3/512/267_Python-256.png"
              unoptimized
              height="60px"
              width="60px"
              alt=""
            ></Image>
          </div>
          <div className=" flex items-center justify-center h-8 md:16 sm:h-auto aspect-square">
            <Image
              src="https://cdn4.iconfinder.com/data/icons/logos-brands-5/24/java-256.png"
              unoptimized
              height="60px"
              width="60px"
              alt=""
            ></Image>
          </div>
        </div>
        <div className="h-40 md:h-32">
          <h1></h1>
        </div>
      </main>
      <div className="bg-black px-3 md:px-32 xl:h-screen h-screen mt-30">
        <div className=" grid grid-cols-1 grid-rows-1 h-screen">
          <div className="self-center">
            <h1 className="text-2xl text-white font-extrabold xl:text-6xl">
              Feel free to connect.<span></span>
            </h1>
            <h1 className="text-3xl mt-10 text-white hover:text-red-600 hover:duration-300 font-extrabold xl:text-7xl xl:mt-60">
              joyetgeorge@gmail.com
            </h1>
            <h1 className="text-4xl mt-4 text-white hover:text-red-600 hover:duration-300 font-extrabold xl:text-5xl xl:mt-10">
              +91 9400 322 519
            </h1>
            <div className="mt-10">
              <a className="text-2xl text-white" href="">
                📍Kannur, Kerala, India
              </a>
            </div>
          </div>
          <div className="self-center mb-2">
            <a className="text-2xl text-white hover:text-red-600" href="">
              GitHub
            </a>
            <a className="text-2xl text-white hover:text-red-600 ml-10" href="">
              Linkedin
            </a>
            <a className="text-2xl text-white hover:text-red-600 ml-10" href="">
              Instagram
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}
