import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Portfolio.module.css";
import Link from 'next/link';

export default function Home() {
  // console.log(data)
  // console.log(data.title)
  return (
    <div className={styles.container}>
      <Head>
        <title>joyetgeorge.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1><Link href="/blogs"><a href="">Blog</a></Link></h1>
      </main>
    </div>
  );
}
